// Imagens SVG locais que sempre funcionam
const propertyImages = {
    apartamento: [
        "images/apartamentos/apt-living.svg",
        "images/apartamentos/apt-cozinha.svg",
        "images/apartamentos/apt-quarto.svg",
        "images/apartamentos/apt-banheiro.svg"
    ],
    casa: [
        "images/casas/casa-frente.svg",
        "images/casas/casa-jardim.svg",
        "images/casas/casa-piscina.svg",
        "images/casas/casa-living.svg"
    ],
    comercial: [
        "images/comercial/sala-reuniao.svg",
        "images/comercial/sala-trabalho.svg",
        "images/comercial/sala-recepcao.svg",
        "images/comercial/sala-area.svg"
    ],
    terreno: [
        "images/terrenos/terreno-vista.svg",
        "images/terrenos/terreno-area.svg",
        "images/terrenos/terreno-acesso.svg",
        "images/terrenos/terreno-mapa.svg"
    ]
};

const properties = [
    {
        id: 1,
        title: "Apartamento Cobertura Duplex",
        type: "apartamento",
        purpose: "venda",
        price: 2500000,
        location: "Jardins, São Paulo - SP",
        address: "Rua Oscar Freire, 500",
        rooms: 4,
        bathrooms: 3,
        garages: 2,
        area: 180,
        description: "Espetacular cobertura duplex no coração dos Jardins. Amplo living com pé direito duplo, cozinha planejada gourmet, 4 suítes completas, terraço com churrasqueira e vista panorâmica da cidade. Prédio com academia, piscina, spa, salão de festas e segurança 24 horas.",
        features: ["Piscina", "Academia", "Churrasqueira", "Terraço", "Elevador", "Portaria 24h", "Vista Panorâmica", "Closet", "Suíte Master", "Lavabo"],
        images: propertyImages.apartamento,
        featured: true
    },
    {
        id: 2,
        title: "Casa de Praia em Condomínio",
        type: "casa",
        purpose: "venda",
        price: 3800000,
        location: "Guarujá, São Paulo - SP",
        address: "Estrada das Mansões, 1500",
        rooms: 5,
        bathrooms: 4,
        garages: 4,
        area: 450,
        description: "Magnífica casa de praia em condomínio fechado de alto padrão. 5 dormitórios sendo 4 suítes, piscina aquecida, área de lazer completa com churrasqueira e forno de pizza. A 300 metros da praia com acesso privativo. Vista mar privilegiada.",
        features: ["Piscina", "Vista Mar", "Churrasqueira", "Closet", "Suítes", "Segurança 24h", "Acesso Praia", "Jardim", "Garagem Coberta", "Home Theater"],
        images: propertyImages.casa,
        featured: true
    },
    {
        id: 3,
        title: "Apartamento 3 Dormitórios",
        type: "apartamento",
        purpose: "aluguel",
        price: 8500,
        location: "Vila Mariana, São Paulo - SP",
        address: "Rua Vergueiro, 2000",
        rooms: 3,
        bathrooms: 2,
        garages: 1,
        area: 95,
        description: "Excelente apartamento bem localizado na Vila Mariana. 3 dormitórios com armários embutidos, living espaçoso, cozinha americana planejada, 2 banheiros completos. Próximo ao metrô e comércios. Prédio com academia e salão de festas.",
        features: ["Armários Embutidos", "Varanda", "Piscina", "Academia", "Salão de Festas", "Portaria 24h", "Elevador"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 4,
        title: "Casa Moderna em Alphaville",
        type: "casa",
        purpose: "venda",
        price: 4200000,
        location: "Alphaville, Barueri - SP",
        address: "Alameda Xingu, 350",
        rooms: 4,
        bathrooms: 5,
        garages: 4,
        area: 520,
        description: "Casa contemporânea de alto padrão em Alphaville. Projeto arquitetônico moderno com linhas limpas e ambientes integrados. 4 suítes master, escritório, adega, piscina com borda infinita, paisagismo projeto paisagístico. Todos os ambientes com automação completa.",
        features: ["Piscina", "Automação", "Adega", "Escritório", "Home Theater", "Jardim", "Garagem", "Suíte Master", "Closet", "Piso Aquecido"],
        images: propertyImages.casa,
        featured: true
    },
    {
        id: 5,
        title: "Sala Comercial Centro",
        type: "comercial",
        purpose: "aluguel",
        price: 12000,
        location: "Centro, São Paulo - SP",
        address: "Av. Paulista, 1000",
        rooms: 4,
        bathrooms: 2,
        garages: 0,
        area: 150,
        description: "Sala comercial no coração da Paulista com 150m². 4 ambientes adaptáveis, recepção, sala de reuniões, banheiro social. Prédio com segurança, elevadores e estacionamento para visitantes. Ideal para escritórios, consultórios ou representações.",
        features: ["Ar Condicionado", "Recepção", "Acesso 24h", "Elevador", "Segurança", "Internet Fibra"],
        images: propertyImages.comercial,
        featured: false
    },
    {
        id: 6,
        title: "Terreno em Condomínio",
        type: "terreno",
        purpose: "venda",
        price: 1800000,
        location: "Mairinque, São Paulo - SP",
        address: "Rua das Palmeiras, 200",
        rooms: 0,
        bathrooms: 0,
        garages: 0,
        area: 1200,
        description: "Terreno plano de 1.200m² em condomínio fechado de alto padrão. Terreno totalmente murado com projeto aprovado para construção de 800m². Infraestrutura completa: água, luz, esgoto. Segurança 24 horas com ronda eletrônica. Zoneamento residencial exclusivo.",
        features: ["Documentação OK", "Projeto Aprovado", "Terreno Plano", "Murado", "Rede Água", "Rede Esgoto", "Segurança 24h"],
        images: propertyImages.terreno,
        featured: false
    },
    {
        id: 7,
        title: "Penthouse na Marginal",
        type: "apartamento",
        purpose: "venda",
        price: 8500000,
        location: "Vila Olímpia, São Paulo - SP",
        address: "Av. das Nações Unidas, 5000",
        rooms: 5,
        bathrooms: 6,
        garages: 4,
        area: 350,
        description: "Exclusivo penthouse na Marginal Pinheiros com vista panorâmica 360°. 5 suítes master com closet e banheira, cozinha gourmet, salão de jogos, adega, espaço wellness com sauna e spa. Terraço privativo com piscina e área gourmet.",
        features: ["Vista Panorâmica", "Piscina Privativa", "Sauna", "Spa", "Home Theater", "Adega", "Closet Master", "Terraço", "Elevador Privativo", "Automação"],
        images: propertyImages.apartamento,
        featured: true
    },
    {
        id: 8,
        title: "Casa de Campo",
        type: "casa",
        purpose: "venda",
        price: 2900000,
        location: "Atibaia, São Paulo - SP",
        address: "Estrada da Serra, 800",
        rooms: 4,
        bathrooms: 3,
        garages: 3,
        area: 380,
        description: "Charme e aconchego em casa de campo a 60km de São Paulo. 4 dormitórios, sendo 2 suítes, lareira no living, cozinha espaçosa com fogão a lenha, área de churrasqueira coberta, piscina aquecida e campo de futebol. 5.000m² de terreno com pomar.",
        features: ["Lareira", "Piscina", "Churrasqueira", "Campo", "Pomar", "Fogão a Lenha", "Jardim", "Lago"],
        images: propertyImages.casa,
        featured: false
    },
    {
        id: 9,
        title: "Loft Industrial",
        type: "apartamento",
        purpose: "aluguel",
        price: 6500,
        location: "Vila Madalena, São Paulo - SP",
        address: "Rua Aspicuelta, 450",
        rooms: 2,
        bathrooms: 1,
        garages: 1,
        area: 85,
        description: "Loft estilo industrial no coração da Vila Madalena. Pé direito alto, tijolinho aparente, projetos sob medida. 2 ambientes amplos integrados com cozinha gourmet, 2 dormitórios e banheiro completo. Próximo a bares, restaurantes e estação de metrô.",
        features: ["Estilo Industrial", "Pé Direito Alto", "Tijolinho", "Móveis Planejados", "Ar Condicionado", "Varanda"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 10,
        title: "Sobrado em Bairro Fechado",
        type: "casa",
        purpose: "venda",
        price: 1650000,
        location: "Campo Belo, São Paulo - SP",
        address: "Rua das Acácias, 150",
        rooms: 3,
        bathrooms: 2,
        garages: 2,
        area: 180,
        description: "Sobrado em bairro fechado com excelente localização no Campo Belo. 3 dormitórios sendo 1 suíte master, living com lareira, cozinha planejada, área de serviço completa. Condomínio com playground, academia e segurança.",
        features: ["Lareira", "Piscina Condomínio", "Playground", "Academia", "Portaria 24h", "Quintal"],
        images: propertyImages.casa,
        featured: false
    },
    {
        id: 11,
        title: "Apartamento Garden",
        type: "apartamento",
        purpose: "venda",
        price: 980000,
        location: "Moema, São Paulo - SP",
        address: "Av. Moema, 300",
        rooms: 2,
        bathrooms: 1,
        garages: 1,
        area: 75,
        description: "Charmoso apartamento garden com 75m² em Moema. Living integrado à cozinha americana, 2 dormitórios com armários, banheiro social, área externa privativa com jardim de 30m². Próximo ao parque Ibirapuera e estação de metrô.",
        features: ["Garden", "Área Externa", "Armários", "Ar Condicionado", "Próximo Metro", "Parque"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 12,
        title: "Chácara para Eventos",
        type: "casa",
        purpose: "venda",
        price: 4500000,
        location: "Cotia, São Paulo - SP",
        address: "Estrada do Embu, 2500",
        rooms: 6,
        bathrooms: 5,
        garages: 10,
        area: 2500,
        description: "Linda chácara especializada em eventos e confraternizações. Capacidade para 200 pessoas, salão de festas climatizado, cozinha industrial completa, 6 suítes para hospedagem, piscina adulto e infantil, campo de futebol, quadras de tênis e vôlei.",
        features: ["Salão de Festas", "Cozinha Industrial", "Piscina", "Campos", "Quadras", "Hospedagem", "Estacionamento", "Área Verde"],
        images: propertyImages.casa,
        featured: true
    },
    {
        id: 13,
        title: "Studio Completo no Centro",
        type: "apartamento",
        purpose: "aluguel",
        price: 2800,
        location: "República, São Paulo - SP",
        address: "Avenida São Luís, 187",
        rooms: 1,
        bathrooms: 1,
        garages: 0,
        area: 35,
        description: "Studio moderno e aconchegante no coração de São Paulo. Ideal para solteiros ou casais. Completamente mobiliado com sofá-cama, mesa de trabalho, kitchenette equipada, TV smart e Wi-Fi. Prédio com lavanderia coletiva e segurança 24 horas.",
        features: ["Mobiliado", "Wi-Fi", "TV Smart", "Kitchenette", "Lavanderia", "Segurança 24h", "Ar Condicionado", "Próximo Metro"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 14,
        title: "Apartamento 2 Quartos Mobiliado",
        type: "apartamento",
        purpose: "aluguel",
        price: 4200,
        location: "Pinheiros, São Paulo - SP",
        address: "Rua dos Pinheiros, 870",
        rooms: 2,
        bathrooms: 1,
        garages: 1,
        area: 65,
        description: "Apartamento mobiliado de 65m² em Pinheiros, um dos bairros mais desejados de São Paulo. 2 quartos com armários, sala espaçosa, cozinha americana completa. Ótima iluminação natural e ventilação. Próximo a bares, restaurantes e comércio variado.",
        features: ["Mobiliado", "Armários", "Varanda", "Próximo Comercio", "Ar Condicionado", "Elevador", "Garagem"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 15,
        title: "Cobertura 3 Suítes na Paulista",
        type: "apartamento",
        purpose: "venda",
        price: 4500000,
        location: "Bela Vista, São Paulo - SP",
        address: "Avenida Paulista, 1578",
        rooms: 3,
        bathrooms: 4,
        garages: 3,
        area: 220,
        description: "Espetacular cobertura na Avenida Paulista com vista panorâmica para o skyline de São Paulo. 3 suítes master, living com pé direito duplo de 6 metros, cozinha gourmet com ilha, terraço privativo com churrasqueira e jacuzzi. Acabamentos de alto padrão em mármore e madeira.",
        features: ["Vista Panorâmica", "Jacuzzi", "Churrasqueira", "Terraço", "Pé Direito Alto", "Suíte Master", "Elevador Privativo", "Automação"],
        images: propertyImages.apartamento,
        featured: true
    },
    {
        id: 16,
        title: "Apartamento Garden com Quintal",
        type: "apartamento",
        purpose: "venda",
        price: 890000,
        location: "Itaim Bibi, São Paulo - SP",
        address: "Rua Roque Petrella, 350",
        rooms: 2,
        bathrooms: 1,
        garages: 1,
        area: 72,
        description: "Charmoso apartamento tipo garden com quintal privativo de 25m² em localização privilegiada no Itaim Bibi. 2 dormitórios com armários planejados, living integrado à cozinha americana, banheiro social reformado. Quintal perfeito para plantas e pets. Condomínio tranquilo com área verde.",
        features: ["Quintal Privativo", "Área Verde", "Pets Permitidos", "Armários", "Mobiliado", "Próximo Parque", "Transporte Público"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 17,
        title: "Loft Duplex Industrial",
        type: "apartamento",
        purpose: "aluguel",
        price: 7500,
        location: "Vila Madalena, São Paulo - SP",
        address: "Rua Aspicuelta, 520",
        rooms: 2,
        bathrooms: 2,
        garages: 1,
        area: 95,
        description: "Incrível loft duplex estilo neoyorkino na Vila Madalena. Pé direito de 5 metros no living, mezanino com quarto master, segundo dormitório no térreo, 2 banheiros completos. Acabamento em tijolinho aparente, cimento queimado e madeira de lei. Arte urbana nas paredes.",
        features: ["Duplex", "Pé Direito Alto", "Mezanino", "Estilo Industrial", "Tijolinho", "Arte Urbana", "Próximo Bares", "Ar Condicionado"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 18,
        title: "Apartamento Alto Padrão Brooklin",
        type: "apartamento",
        purpose: "venda",
        price: 1850000,
        location: "Brooklin Novo, São Paulo - SP",
        address: "Avenida Roque Petrella, 450",
        rooms: 3,
        bathrooms: 2,
        garages: 2,
        area: 110,
        description: "Apartamento de 110m² em prédio novo no Brooklin Novo. 3 dormitórios sendo 1 suíte master com closet, living com varanda gourmet, cozinha americana completa com bancada em granito. Infraestrutura para ar condicionado splits em todos os cômodos. Vaga de garagem para 2 carros.",
        features: ["Prédio Novo", "Varanda Gourmet", "Suíte Master", "Closet", "Granito", "Ar Condicionado", "2 Vagas", "Elevador"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 19,
        title: "Cobertura Vista Mar - Santos",
        type: "apartamento",
        purpose: "venda",
        price: 2200000,
        location: "Pompéia, Santos - SP",
        address: "Avenida Pedro Lessa, 1200",
        rooms: 4,
        bathrooms: 3,
        garages: 2,
        area: 165,
        description: "Magnífica cobertura de 165m² com vista mar 180° na orla de Santos. 4 dormitórios, sendo 2 suítes, living espaçoso com varanda, cozinha gourmet, terraço com churrasqueira e spa. Último pavimento - sem vizinhos em cima. Condomínio com piscina, academia e beach club.",
        features: ["Vista Mar", "180°", "Terraço", "Churrasqueira", "Spa", "Beach Club", "Piscina", "Academia"],
        images: propertyImages.apartamento,
        featured: true
    },
    {
        id: 20,
        title: "Kitnet Completa",
        type: "apartamento",
        purpose: "aluguel",
        price: 1800,
        location: "Cambuci, São Paulo - SP",
        address: "Rua da Graça, 280",
        rooms: 1,
        bathrooms: 1,
        garages: 0,
        area: 28,
        description: "Kitnet compacta e bem planejada no Cambuci, região central de São Paulo. Ideal para estudantes ou jovens profissionais. Mobiliada com cama box, estante, guarda-roupa, geladeira, fogão e TV. Internet fibra instalada. Fácil acesso ao metrô Anhangabaú.",
        features: ["Mobiliada", "Internet Fibra", "Geladeira", "TV", "Próximo Metro", "Centro", "Seguro", "Lavanderia"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 21,
        title: "Penthouse Luxo Itaim",
        type: "apartamento",
        purpose: "venda",
        price: 6500000,
        location: "Itaim Bibi, São Paulo - SP",
        address: "Rua Professor Atílio Innocenti, 800",
        rooms: 4,
        bathrooms: 5,
        garages: 4,
        area: 280,
        description: "Exclusivo penthouse de 280m² no coração do Itaim Bibi. 4 suítes master, todas com closet e banheiro com hidromassagem, living de 60m² com pé direito de 7 metros, cozinha gourmet com ilha, adega para 300 garrafas, terraço privativo com piscina aquecida e jardim vertical.",
        features: ["Piscina Privativa", "Aquecida", "Hidro", "Adega", "Home Theater", "Automação", "Closet Master", "Jardim Vertical"],
        images: propertyImages.apartamento,
        featured: true
    },
    {
        id: 22,
        title: "Apartamento 1 Quarto",
        type: "apartamento",
        purpose: "aluguel",
        price: 2200,
        location: "Vila Prudente, São Paulo - SP",
        address: "Rua Professor José Autran, 450",
        rooms: 1,
        bathrooms: 1,
        garages: 0,
        area: 38,
        description: "Apartamento de 1 quarto bem localizado na Vila Prudente, próximo ao Parque das Lauráceas e com fácil acesso ao metrô. Apartamento novo, nunca habitado, com piso laminado, azulejos até o teto no banheiro, cozinha americana com nicho para máquina de lavar.",
        features: ["Novo", "Piso Laminado", "Máquina Lavar", "Próximo Metro", "Parque", "Transporte", "Iluminação LED", "Portaria"],
        images: propertyImages.apartamento,
        featured: false
    },
    {
        id: 23,
        title: "Cobertura Duplex Jardins",
        type: "apartamento",
        purpose: "venda",
        price: 5800000,
        location: "Jardins, São Paulo - SP",
        address: "Rua da Consolação, 2100",
        rooms: 4,
        bathrooms: 4,
        garages: 3,
        area: 240,
        description: "Cobertura duplex de 240m² em localização privilegiada na Rua da Consolação. Primeiro pavimento: living de 50m², sala de jantar, cozinha gourmet, lavabo, lavanderia completa. Segundo pavimento: 4 suítes master, terraço com churrasqueira e vista para a cidade. Acabamentos em mármore Travertino.",
        features: ["Duplex", "Terraço", "Churrasqueira", "Marmore Travertino", "Lavanderia", "Suítes Master", "Vista Cidade", "Portaria Blindada"],
        images: propertyImages.apartamento,
        featured: true
    },
    {
        id: 24,
        title: "Apartamento Compacto",
        type: "apartamento",
        purpose: "aluguel",
        price: 1600,
        location: "Penha, São Paulo - SP",
        address: "Rua Dr. João Evangelista Costa, 120",
        rooms: 1,
        bathrooms: 1,
        garages: 0,
        area: 30,
        description: "Kitnet compacta ideal para estudantes ou pessoas sozinhas. Bem iluminada, com janela grande, ventilador de teto, geladeira e fogão. Próximo ao metrô Penha e ao Shopping Center Penha. Região com comércio local abundante, supermercados e farmácias 24 horas.",
        features: ["Econômico", "Próximo Metro", "Ventilador", "Geladeira", "Fogão", "Comércio Local", "Farmácia 24h", "Transporte"],
        images: propertyImages.apartamento,
        featured: false
    }
];
